# Generated by Django 5.0.6 on 2026-06-15 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_add_import_session_and_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('usd_to_inr_rate', models.DecimalField(decimal_places=4, default='83.5000', max_digits=8)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_csv', models.TextField(blank=True)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_row_number', models.PositiveIntegerField()),
                ('anomaly_type', models.CharField(choices=[('duplicate', 'Duplicate Expense'), ('missing_field', 'Missing Required Field'), ('invalid_amount', 'Invalid Amount'), ('negative_amount', 'Negative Amount (Refund)'), ('zero_amount', 'Zero Amount'), ('date_format', 'Date Format Issue'), ('ambiguous_date', 'Ambiguous Date'), ('currency_conversion', 'Currency Conversion Required'), ('unknown_user', 'Unknown User'), ('participant_mismatch', 'Participant Mismatch'), ('settlement_as_expense', 'Settlement Disguised as Expense'), ('split_inconsistency', 'Split Inconsistency'), ('name_normalization', 'Name Normalization Applied'), ('membership_violation', 'Membership Timeline Violation'), ('split_type_invalid', 'Invalid Split Type'), ('decimal_precision', 'Decimal Precision Adjusted')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('original_data', models.JSONField(default=dict)),
                ('action_taken', models.CharField(choices=[('imported', 'Imported'), ('skipped', 'Skipped'), ('converted_to_settlement', 'Converted to Settlement'), ('normalized_and_imported', 'Normalized and Imported'), ('currency_converted_and_imported', 'Currency Converted and Imported'), ('flagged_duplicate_pending_review', 'Flagged as Duplicate — Pending Review'), ('treated_as_refund', 'Treated as Refund — Expense Skipped'), ('rounded_and_imported', 'Rounded to 2dp and Imported')], max_length=50)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importsession')),
            ],
            options={
                'db_table': 'import_issues',
                'ordering': ['csv_row_number'],
            },
        ),
    ]
